In [34]:

import numpy as np
a = np.array([1,2,3]) # 1차원 array [1,2,3] 생성
print(type(a))
print(a.shape)
print(type(a.shape))
print(a[0], a[1], a[2])
a[0] = 5
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
<class 'tuple'>
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [38]:
import numpy as np
a = np.zeros((2,2)) # 모든 값이 0인 2x2 array 생성
print(a)
b = np.ones((1,2)) # 모든 값이 1인 1x2 array 생성
print(b)
c = np.full((2,2), 7) # 모든 값이 7인 2x2 array 생성
print(c)
d = np.eye(2) # 2x2 단위행렬(Identity matrix) 생성
print(d)
e = np.random.random((2,2)) # 0~1 랜덤 값을 가지는 2x2 array 생성
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.81390873 0.28912663]
 [0.50044703 0.0680537 ]]


In [41]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# 첫번째 행의 처음부터 2 앞까지(0,1), 두번째 행에서
# 1부터 3 앞까지(1,2)의 값들을 떠와 b에 할당.
# 따라서 b 는 다음과 같은 2x2 array:
# [[2 3]
# [6 7]]
b = a[:2, 1:3]
print(b)
print(a[0, 1])
b[0, 0] = 77
b[0, 1] = 77
print(a)
print(a[0, 1])
# Slicing을 한다고 해서 값을 복사해가는 것이 아니므로
# 값의 변화가 동시에 일어남

[[2 3]
 [6 7]]
2
[[ 1 77 77  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
77


In [42]:
import numpy as np
# 2차원 배열(3x4) 생성
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# 두 번째 행의 값들을 모두 가져오는 두 가지 방법
row_r1 = a[1, :] # 1차원 행렬 (4,)
row_r2 = a[1:2, :] # 2차원 행렬 (1x4) – 기존 차원 유지
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
# 두 번째 열의 값들을 모두 가져오는 두 가지 방법
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [54]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b =np.array([a[0,0],a[1,1],a[2,0]])
print(b)
print(type(b))
print(b.shape)

print(np.array([a[[0,1,2],[0,1,0]]]))

[1 4 5]
<class 'numpy.ndarray'>
(3,)
[[1 4 5]]


In [55]:
import numpy as np
# 2차원 배열(4x3) 생성
# [[ 1 2 3]
# [ 4 5 6]
# [ 7 8 9]
# [ 10 11 12]]
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b]) # [1 6 7 11] #np.array(range(4)) 
a[np.arange(4), b] += 10
print(a) # array([[11, 2, 3],
# [ 4, 5, 16],
# [17, 8, 9],
# [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [58]:
import numpy as np
x = np.array([1, 2])
print(x.dtype) # prints “int64”
x = np.array([1.0, 2.0])
print(x.dtype) # “float64”
x = np.array([1, 2], dtype=np.int64) # 데이터타입 명시
print(x.dtype) # “int64”

int64
float64
int64


In [60]:
import numpy as np
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
# Elementwise sum
# [[ 6.0 8.0]
# [10.0 12.0]]
print(x + y)
print(np.add(x, y))
# Elementwise difference
# [[-4.0 -4.0]
# [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))
# Elementwise product
# [[ 5.0 12.0]
# [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))
# Elementwise division
# [[0.2 0.33333333]
# [0.42857143 0.5 ]]
print(x / y)
print(np.divide(x, y))
# Elementwise square root
# [[1. 1.41421356]
# [1.73205081 2. ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [63]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
# v · w = 219
print(v.dot(w))
print(np.dot(v, w))
# 매트릭스 / 벡터 곱; [29 67]
print(x.dot(v))
print(np.dot(x, v))
# 매트릭스 / 매트릭스 곱;
# [[19 22]
# [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [64]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
print(np.sum(x)) # 모든 원소의 합
print(np.sum(x, axis=0)) # 각 열의 합
print(np.sum(x, axis=1)) # 각 행의 합

10
[4 6]
[3 7]


In [84]:
a=np.ones((2,3,4))
print(a)
print(np.sum(a))
print(np.sum(a,axis=0))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
24.0
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [85]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T) 
# 전치행렬 (Transposed mat.)
v = np.array([1,2,3])
print(v) # prints “[1 2 3]”
print(v.T) # prints “[1 2 3]”

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [89]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x) # x와 같은 shape의 빈 매트릭스 만들기
# x의 각 행에 v와 elementwise 합을 하여 y의 해당 행에 할당
for i in range(4):
    y[i] = x[i] + v
# [[ 2 2 4]
# [[ 5 5 7]
# [[ 8 8 10]
# [ 11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [91]:
a=np.array([1,2,3])
a1=a.reshape([3,1])
print(a1.shape)
print(a)
print(a1)

(3, 1)
[1 2 3]
[[1]
 [2]
 [3]]


In [121]:
a=np.array([[1,1],[2,1]])
b=np.array([15,25])
c=np.linalg.inv(a)
print(c)
print(b)
k=np.multiply(b, c)
print(k)
print(np.sum(k, axis=1))



[[-1.  1.]
 [ 2. -1.]]
[15 25]
[[-15.  25.]
 [ 30. -25.]]
[10.  5.]


In [122]:
a=np.array([[1,1],[2,1]])
b=np.array([[15],[25]])
c=np.linalg.inv(a)
print(c)
print(b)
k=np.multiply(b, c)
print(k)
print(np.sum(k, axis=0))

[[-1.  1.]
 [ 2. -1.]]
[[15]
 [25]]
[[-15.  15.]
 [ 50. -25.]]
[ 35. -10.]
